<?php defined('BASEPATH') OR exit('No direct script access allowed');
/**
* Pancake
*
* A simple, fast, self-hosted invoicing application
*
* @package     Pancake
* @author      Pancake Dev Team
* @copyright   Copyright (c) 2010, Pancake Payments
* @license     http://pancakeapp.com/license
* @link        http://pancakeapp.com
* @since       Version 1.0
*/

// ------------------------------------------------------------------------

$lang = array(

	/** Global Words **/
	'global:overview'				=> 'Resumen',
	'global:error'					=> 'Error',
	'global:pancakeby7am'			=> 'Pancake :1',
	'global:allrelatedmediacopyright'		=> 'Pancake y todos los medios relacionados tienen Copyright :1 :2',
	'global:insecure_action'		=> 'Acción insegura se intentó pero fue atrapada',
	'global:disabled_in_demo'		=> 'Algunas funciones de esta página están deshabilitadas para la demo.',
	'global:estimates'				=> 'Presupuestos',
	'global:estimate'				=> 'Presupuesto',
	'global:incomplete_tasks'		=> 'Tareas incompletas',
	'global:completed_tasks'		=> 'Tareas completas',
	'global:projects'				=> 'Proyectos',
	'global:tickets'				=> 'Tickets',
	'global:project'				=> 'Proyecto',
	'global:upload_failed'			=> 'Hubo un problema al subir el archivo. Por favor, vuelva a intentarlo. Si el problema persiste, póngase en contacto con support@pancakeapp.com.',
	'global:upload_not_allowed'		=> 'El tipo de archivo del archivo que estaba tratando de subir no está permitido. Si necesita cargar un archivo de ese tipo, por favor comprimirlo en un archivo .zip o cualquier otro formato de archivo que usted podría encontrar apropiado.',
	'global:copied'					=> 'Copiado!',
	'global:sentbutunpaid'			=> 'Pendiente (Enviado, pero sin pagar)',
	'global:task'					=> 'Tarea',
	'global:clients'				=> 'Clientes',
	'global:access_denied'                      => "Acceso negado",
	'global:users'					=> 'Usuario',
	'global:send_to_client'			=>  'Enviado al cliente',
	'global:couldnotsendemail'		=> 'No se pudo enviar el e-mail. Favor verificar la configuracion.',
	'global:emailsent'				=> 'El correo electrónico ha sido enviado!',
	'global:yes'					=> 'Si',
	'global:no'						=> 'No',
	'global:notyetsent'				=> 'No enviado al cliente',
	'global:dontshowagain'			=> "No mostrar nuevamente",
	'global:enable'					=> 'Habilitar',
	'global:is_enabled'				=> 'Habilitado?',
	'global:is_completed'			=> 'Completado?',
	'global:Y'						=> 'S',
	'global:N'						=> 'N',
	'global:notes'					=> 'Notas',
	'global:description'			=> 'Descripción',
	'global:backtoadmin'			=> 'Volver al Admin',
	'global:type'					=> 'Tipo',
	'global:name'    				=>  'Nombre',
	'global:first_name'     		=>  'Primer nombre',
	'global:last_name'     			=>  'Apellido',
	'global:company'    			=>  'Compañía',
	'global:for'    				=>  'para',
	'global:from'   				=>  'de',
	'global:phone'     				=>  'Teléfono',
	'global:email'      			=>  'Email',
	'global:contacts'   			=>  'Contactos',
	'global:week'					=> 'Semanalmente',
	'global:na'						=> 'N/A',
	'global:quarterly'				=> 'Trimestralmente',
	'global:every_six_months'		=> 'Cada 6 meses',
	'global:statistics' => "Estadísticas",
	'global:biyearly'				=> 'Cada 2 años',
	'global:month'					=> 'Mensualmente',
	'global:year'					=> 'Anualmente',
	'global:fax'					=>	'Fax',
	'global:mobile'					=>	'Móvil',
	'global:address'				=>	'Dirección',
	'global:api_key'				=> 'Llave de API',
	'global:website'				=>	'Sitio',
	'global:action'					=>	'Acción',
	'global:items'					=>	'Items',
	'global:reusableinvoiceitems'	=> 'Items de factura reutilizables',
	'global:reusableinvoiceitems_description'	=> 'Deberías utilizar Elementos de factura reutilizables cuando se desea volver a utilizar el mismo artículo en diferentes facturas. Para utilizarlos al crear o editar una factura, simplemente comienza a escribir el nombre del elemento que ha guardado y se autocompletarán los detalles del elemento para usted.',
	'global:create_invoice_estimate'	=>	'Crear facturas y presupuestos para recolectar dinero.',
	'global:createinvoice' 			=> 'Crear factura',
	'global:paid' 					=> 'Pagado',
	'global:unpaid'					=> 'Sin pagar',
	'global:overdue'				=> 'Atrasado',
	'global:time_entries'			=> 'Entradas de tiempo',
	'global:invoices'				=> 'Facturas',
	'global:invoice'				=>	'Factura',
		'global:tasks' => 'Tareas',
	'global:estimate' 				=> 'Presupuesto',
	'global:dashboard'				=> 'Panel de control',
	'global:settings'				=> 'Ajustes',
	'global:plugins'				=> 'Plugins',
	'global:installed'				=> 'Instalado',
	'global:changepassword'			=> 'Cambiar Password',
	'global:logout' 				=> 'Salir',
	'global:status'					=> 'Estatus',
	'global:client'					=> 'Cliente',
	'global:user'					=> 'Usuario',
	'global:title'					=> 'Título',
	'global:subtitle'				=> 'Subtítulo',
	'global:to'						=> 'A (separar múltiples direcciones con una coma)',
	'global:subject'				=> 'Asunto',
	'global:thanks'					=> 'Gracias!',
	'global:proposals'				=> 'Propuestas',
	'global:proposal'				=> 'Propuesta',
	'global:reports'				=> 'Reportes',
	'global:item'					=> 'Item',
	'global:report'					=> 'Reporte',
	'global:saveandinsert'			=> 'Guardar e insertar',
	'global:details'				=>	'Detalles',
	'global:license_key'			=> 'Llave de licencia',
	'global:version'				=> 'Version :1',
	'global:content'				=> 'Contenido',
	'global:add'					=>	'Agregar',
	'global:edit'					=>	'Editar',
	'global:resend'					=>	'Re enviar',
	'global:sent'					=> 'Enviado',
	'global:not_sent'				=> 'No enviado',
	'global:view'					=>	'Ver',
	'global:delete'					=>	'Borrar',
	'global:remove'					=>	'Remover',
	'global:sort'					=>	'Ordenar',
	'global:deleteitem'				=> 'Borrar ítem',
	'global:dragtoreorder'			=> 'Arrastrar para reordenar',
	'global:start'					=> 'Comenzasr',
	'global:stop'					=> 'Parar',
	'global:start_timer'			=> 'Iniciar temporizador',
	'estimates:create' => "Crear Presupuesto",
	'global:stop_timer'				=> 'Parar temporizador',
	'global:created'				=>	'Creado',
	'global:updated'				=>	'Actualizado',
	'global:update'					=>	'Actualizar',
	'global:update_available'					=>	':1 Actualización disponible',
	'global:updates_available'					=>	':1 Actualizaciones disponibles',
	'global:downloadpdf'			=> 'Descargar PDF',
	'global:yesdelete'				=> 'Si, borrar!',
	'global:confirm_emphisised'		=>	'No hay vuelta atrás!',
	'global:color'					=> 'Color',
	'global:save'					=> 'Guardar',
	'global:unknown'				=> 'Desconocido',
	'global:upload_ini_size'		=> 'El archivo que has subido excede el límite de tamaño impuesto por la instalación de PHP.',
	'global:upload_error'			=> 'Ocurrió un problema al subir el archivo. Por favor, inténtalo de nuevo.',
	'global:recurring'				=> 'Recurrente',
	'global:unsent'					=> 'Sin enviar',
	'global:converttoproject'		=> 'Convertir a Proyecto',
	'global:converttoinvoice'		=> 'Convertir a Factura',
	'global:viewpdf'				=> 'Ver PDF',
	'global:duplicate'				=> 'Duplicar',
	'global:urltosend'				=>	'Aquí está la url para enviar:',
	'global:copytoclipboard'		=>	'Copiar al portapapeles',
	'global:you_need_pancake_cron_job'		=> 'Para utilizar facturas recurrentes, debes estar ejecutando trabajos CRON con Pancake.',
	'global:if_you_dont_know_how_to_set_it_up'		=> 'Si no sabes cómo configurarlos, <a href="http://pancakeapp.com/documentation/cron"> clic aquí </a>.',
	'global:quick_links'			=> 'Enlaces rápidos',
	'global:view_all'				=> 'Ver todo',
	'global:deleted'				=>	'Borrados',

		'global:add_more' => "Agregar más",
		'global:upload_files' => "Subir archivos",
	'global:optional_increment'		=> '<strong>Opcional</strong> - se autoincrementará',

	'login:ahoy'					=> 'ki wa!',
	'login:readytodothis'			=> 'Listo??',
	'login:sup'						=> 'kipa shushetumare?',
	'global:actions'				=> 'Acciones',
		'global:select' => "--- Seleccionar ---",

	/** Greetings **/
	'global:greetings'	=>	array('Ahoy!', 'Hello,', 'Hey,', 'Sup,'),

		'global:mark_as_unanswered' => 'Marcar sin respuesta',
		'global:mark_as_accepted' => 'Marcar como aceptado',
		'global:mark_as_rejected' => 'Marcar como rechazado',
		'global:reject_estimate' => 'Rechazar presupuesto',
		'global:accept_estimate' => 'Aceptar presupuesto',
		'global:estimate_rejected' => 'Presupuesto rechazado',
		"global:estimate_accepted" => "Presupuesto aceptado",
		'global:reject_proposal' => 'Rechazar propuesta',
		'global:accept_proposal' => 'Aceptar propuesta',
		'global:proposal_rejected' => 'Propuesta rechazada',
		"global:proposal_accepted" => "Propuesta aceptada",
		"global:client_area" => "Área de clientes",
		"global:admin" => "Admin",
		"global:all_settings" => "Todos los ajustes",
		'global:viewable' => 'Visible en el área del cliente',
		'global:not_viewable' => 'No visible en el área del cliente',
		'global:milestones' => "Hitos",

	/** End Greetings **/

	/** Dashboard **/
	'dashboard:collected'		=>	'Recolectado',
	'dashboard:outstanding'		=>	'Pendiente',
	'dashboard:latest_activity'	=>	'Actividad reciente',
		'dashboard:these_are_your_upcoming_tasks' => "Estas son sus próximas tareas, :1.",
	'dashboard:upcoming_tasks' 	=> 	'Próximas tareas',
	/** End Dashboard **/


	/** Users **/

	// ==============================
	// = LOGIN PAGE COMPLETED - Lee =
	// ==============================
	'login:forgotinstructions'	=>	'Introduzca su dirección de correo electrónico para que podamos enviarle un correo electrónico para restablecer su contraseña.',
	'login:reset'				=>	'Resetear &raquo;',
	'login:reset'				=>	'Resetear Password',
	'login:username'			=>	'Usuario',
	'login:password'			=>	'Password',
	'login:changepassword'		=>	'Cambiar Password',
	'login:email'				=>	'Email',
	'login:login'				=>	'Login',
	'login:logout'				=>	'Salir',
	'login:remember'			=>	'Recordarme',
	'login:forgot'				=>	'¿Olvidaste tu contraseña?',
	'login:cancel'				=>	'&laquo; Cancelar',
	/** End Users **/

	/** User Groups **/
	'groups:edit_title'			=> 'Editar Grupo %s',
	'groups:add_title'			=> 'Añadir grupo de usuarios',

	/** Clients **/
	'clients:title'				=>	'Todos los clientes',
	'clients:filter'			=>	'Filtrar Cliente',
	'clients:add'				=>	'Agregar Cliente',
	'clients:removefilter'		=>	'Borrar Filtro',
	'clients:edit'				=>	'Editar Cliente',
	'clients:noclienttitle' 	=> 'Es necesario introducir algunos clientes!',
	'clients:noclientbody'		=> 	'Así que usted puede enviar algunas facturas. Añadir uno ahora?',
	'clients:noclienttitlefilter' 	=> 'No hay clientes que coincidan con tu filtro',
	'clients:hasnoinvoicetitle'		=>	'Genial! el cliente está agregado',
	'clients:hasnoinvoicebody'	=> 	'Crear una factura para ellos y obtener pagos! Añadir una ahora?',
	'clients:added' 			=> 'El cliente ha sido agregado!',
	'clients:edited' 			=> 'El cliente ha sido actualizado!',
	'clients:deleted' 			=> 'El cliente ha sido eliminado!',
	'clients:does_not_exist' 	=> 'Ese cliente no existe!',
	'clients:health_check'		=> 	'Chequeo de salud',
	'clients:all' 				=> 'Todo',
	'clients:delete_title'		=>	'Borrar este cliente?!?!',
	'clients:delete_message'	=>	'¿Seguro que quieres borrar este cliente? <br /> Esto también eliminará todas sus facturas, proyectos y propuestas.',
	'clients:clientaction'		=>	'&nbsp;',
	'clients:passphrase'		=> 'Frase de contraseña',
	'clients:bad_passphrase'	=> 'Frase de contraseña es incorrecta.',
	'clients:total_clients'		=>	'Clientes totales',
	'clients:support'			=>  'Soporte',
	'clients:support_rates'		=>  'Valor de soporte',
	'clients:edit_support_rates'		=>  'Establecer tarifas',
	/** End Clients **/


	/** Contact Log **/
	'contact:title'				=>	'Historial de contacto reciente',
	'contact:method'			=>	'Método de contacto',
	'contact:contact'			=>	'Contacto',
	'contact:subject'			=>	'Sujeto',
	'contact:content'			=>	'Contenido',
	'contact:method'			=>	'Método de contacto',
	'contact:calling_title'		=>	'Llamando cliente ":1"',
	// 'contact:view_all'		=>	'View All',
	/** End Contact Log **/

	/** Invoices **/
	'invoices:markassent'			=> 'Marcar como enviado',
		'invoices:invoicedate'			=> 'Fecha de la factura',
		'invoices:file_name' => "Nombre de archivo",
		'invoices:date_created' => "Fecha de creación",
		'invoices:size' => "Tamaño",
		'invoices:files' => "Archivos",
	'invoices:sentbutunpaid'		=> 'Facturas envíadas al cliente pero aún impagas',
	'invoices:duplicated'			=> 'Duplicado de la factura #:1. El número de la nueva factura es el #:2.',
	'invoices:all'					=>	'Todas las facturas',
	'invoices:empty'				=>	'No hay facturas aún.',
	'invoices:overdue'				=>	'Facturas vencidas',
		'invoices:tax_collected' => "Impuestos recolectados",
	'invoices:paid'					=>	'Facturas pagadas',
	'invoices:recurringinvoices'	=> 'Facturas recurrentes',
	'invoices:unsentinvoices'		=> 'Facturas sin enviar',
	'invoices:unpaid'				=>	'Facturas impagas',
	'invoices:thisinvoicewaspaidon'	=> 'Esta factura se pagó el :1. Gracias!',
	'invoices:senton'				=> 'Enviado el :1',
	'invoices:lastsenton'				=> 'Última enviada el :1 a las :2',
	'invoices:paidon'				=> 'Pagada el :1',
	'invoices:paidonsingle'			=>	'Pagada el',
	'invoices:thisinvoiceisunpaid'	=> "Esta factura no ha sido pagada aún.",
	'invoices:noinvoicetitle'		=>	'No hay facturas pendientes!',
		'invoices:noinvoicesforthefilteredclient' => "No tienes facturas para :1.",
	'invoices:noinvoicebody'		=>	'Deberías crear una factura ahora! <br /> Los clientes aman las facturas!',
	'invoices:send_now_title'		=> 'Enviar factura ahora?',
	'invoices:send_now_body'		=> 'Rellene el siguiente formulario y enviaremos la factura para usted.',
	'invoices:newinvoice'			=>	'Crear factura',
	'invoices:send_now'				=> 'Enviar factura',
	'invoices:timequantity'			=> 'Tiempo/Cantidad',
	'invoices:ratewithcurrency'		=> 'Tarifa (:1)',
	'invoices:taxable' 				=> 'Imponible',
	'invoices:total' 				=> 'Total',
	'invoices:amount'				=>	'Monto',
	'invoices:due'					=>	'Vence',
	'invoices:subtotal'				=> 'Subtotal',
	'invoices:totaltax'				=> 'Impuesto total',
	'invoices:filestodownload'		=> 'Archivos para descargar',
	'invoices:added'				=> 'La factura ha sido añadida!',
	'invoices:fileswillbeavailableafterpay'		=> 'Estos archivos estarán disponibles para su descarga una vez que la factura haya sido pagado en su totalidad.',
	'invoices:no_payment_gateways_enabled'		=> 'No hay pasarelas de pago, lo que podría hacer que sea difícil de pagar. Habilitar en <a href=":1"> Ajustes </a>',
	'invoices:invoicenumber'		=> 'Factura #:1',
	'invoices:number'				=> 'Factura #',
	'invoices:type'					=>	'Tipo de factura',
	'invoices:is_recurring'			=> 'Recurrente?',
	'invoices:is_paid'				=> 'Pagado?',
	'invoices:is_sent'				=> 'Enviado?',
	'invoices:date_entered'			=> 'Fecha de creación',
	'invoices:delete_title'			=>	'Borrar esta factura?',
		'items:select_time_entry' => 'Entrada temporal',
	'invoices:delete_message'		=>	'Estás seguro que quieres eliminar esta factura?',
	'invoices:create'				=> 'Crear factura',
	'invoices:edit'					=> 'Editar factura',
	'invoices:amountrequired'		=> 'Se requiere que el campo Cantidad',
	'invoices:currencydoesnotexist'	=> 'Esta moneda no existe.',
	'invoices:unique_id'			=> 'ID único',
	'invoices:willreoccurin'		=> 'Esta factura re ocurrirá el :1.',
	'invoices:willbesentautomatically'		=> 'El cliente será notificado por correo electrónico acerca de esta factura el :1.',
	'invoices:thisisareoccurrence'		=> 'Esta factura es una repetición de la factura :1.',
	'invoices:clientlastnotifiedon'		=> 'El cliente fue notificado por correo electrónico acerca de esta factura el :1.',
	'invoices:simple'				=> 'Simple',
	'invoices:simple_help'			=> 'Una factura sencilla no tiene elementos de línea. Simplemente un total.',
	'invoices:detailed'				=> 'Detallada',
	'invoices:detailed_help'		=> 'Facturas detalladas permitirá tener varios elementos de línea.',
	'invoices:estimate_help'		=> 'Los presupuestos son facturas detalladas que no son facturables.',
	'invoices:unpaid_totalamount'	=>	'Sin pagar / Monto total',
	'invoices:saveinvoice'			=> 'Guardar factura',
	'invoices:deleted'				=> 'La factura ha sido eliminada!',
	'invoices:view'					=> 'Ver factura',
	'invoices:is_viewable'			=>	'Mostrar en el área del cliente?',
	'invoices:no_invoices'			=> 'No hay facturas.',
	'invoices:addedsuccess'			=>	'Has agregado una factura por',
	'invoices:invoice'				=>	'factura',
	'invoices:addedconf'			=>	'Has agregado una factura # <strong>:1</strong>, totalizando <strong>:2</strong> por :3:4.',
	'invoices:preview'				=>	'Previsualizar factura',
	'invoices:editinvoice'			=>	'Editar factura #:1',
	'invoices:messageupdated'		=>	'La factura ha sido actualizada!',
	'invoices:resend'				=>	'Reenviar factura',
	'invoices:client_viewed'		=>	':1 vista <a href=":2">factura #:3</a> el :4',
	'invoices:client_paid'			=>	':1 pagada <a href=":2">factura #:3</a> el :4',
	'invoice:paid_amount'			=>	'Monto pagado',
	/** End Invoices **/

	/** Estimates **/
	'estimates:attachedtoproposal'		=> 'Se adjunta a la propuesta #:1',
	'estimates:duplicated'			=> 'Duplicado presupuesto #:1. El número del nuevo presupuesto es #:2.',
	'estimates:alltitle'			=>	'Todos los presupuestos',
	'estimates:attachingtoproposal'		=>     'Agregando presupuesto a la propuesta, por favor espere...',
	'estimates:delete_title'		=>	'Borrar este presupuesto?',
	'estimates:delete_message'		=>	'Estás seguro que quieres eliminar este presupuesto?',
	'estimates:createnew'			=>	'Crear presupuesto',
	'estimates:generate_estimate'		=> 'Generar presupuesto',
	'estimates:converted'			=> 'Presupuesto #:1 convertido a proyecto.',
	'estimates:converted_to_invoice'			=> 'Presupuesto #:1 convertido a factura.',
	'estimates:noestimatetitle'		=>	'No tienes presupuestos',
	'estimates:noestimatesforthisclient'	=>	'No tienes presupuestos para este cliente.',
		'estimates:noestimatesforthefilteredclient' => "No tienes presupuestos para :1.",
	'estimates:deleted'				=> 'El presupuesto ha sido eliminado!',
	'estimates:noestimatebody'		=>	'Crear uno ahora?',
	'estimates:estimatenumber'		=>	'Presupuesto #:1',
	'estimates:view'				=> 'Ver presupuesto',
	'estimates:no_estimates'		=> 'No hay presupuestos.',
	'estimates:addedsuccess'		=>	'Has agregado un presupuesto para',
	'estimates:estimate'			=>	'presupuesto',
	'estimates:added'				=>	'El presupuesto se ha añadido exitosamente',
	'estimates:addedconf'			=>	'Ha agregado presupuesto # <strong> :1 </ strong>, por un total de <strong> :2 </ strong> para :3:4.',
	'estimates:send_now_title'		=> 'Enviar presupuesto ahora?',
	'estimates:send_now_body'		=> 'Rellena el siguiente formulario y enviaremos el presupuesto.',
	'estimates:send_now'			=>	'Enviar presupuesto',
	'estimates:edit'				=>	'Editar presupuesto',
	'estimates:preview'				=>	'Previsualizar presupuesto',
	'estimates:editestimate'		=>	'Editar presupuesto #:1',
	'estimates:messageupdated'		=>	'El presupuesto ha sido actualizado!',
	'estimates:client_viewed'		=>	':1 ver <a href=":2">presupuesto #:3</a> el :4',
	'estimates:client_accepted'		=>	':1 aceptado <a href=":2">presupuesto #:3</a> el :4',
	'estimates:client_rejected'		=>	':1 rechazado <a href=":2">presupuesto #:3</a> el :4',
	'estimates:resend'				=>	'Reenviar presupuesto',
	'estimates:estimatedate'			=> 'Fecha estimada',
	/** End Estimates **/

	/** Projects **/
	'projects:status_id'			=> 'Estado de la tarea',
	'projects:projected'			=> 'Proyectado',
	'projects:projected_hours'		=> 'Horas proyectadas',
	'projects:navigationitem'		=> 'Proyectos',
	'projects:hours_worked'			=> 'Número de horas trabajadas',
	'projects:hours_worked_short'	=> 'Horas trabajadas',
	'projects:alltitle'				=>	'Todos los proyectos',
	'projects:totalprojects'		=>	'Total Proyectos',
	'projects:noprojecttitle'		=> 'No hay proyectos todavía!',
	'projects:noprojecttext'		=> 'Quieres crear uno ahora? ',
	'projects:add'					=> 'Crear proyecto',
	'projects:createfromtemplate'	=> 'Crear proyecto desde plantilla',
	'projects:doesnotexist'			=> 'El proyecto que estás tratando de acceder no existe.',
	'projects:edit'					=> 'Editar proyecto',
	'projects:delete'				=> 'Borrar proyecto',
	'projects:project'				=> 'Proyecto',

		'projects:new_project_from_estimate_without_number' => "Nuevo proyecto desde presupuesto",
		'projects:new_project_from_estimate_with_number' => "Nuevo proyecto desde presupuesto nro #:1",

	'projects:due_date'				=> 'Fecha de entrega',
	'projects:is_completed'			=> 'Completado?',
	'projects:manage_project'		=> 'Gestionar proyecto',
	'projects:areyousuredeletetask'	=> '¿Seguro que quieres eliminar esta tarea?',
	'projects:add_time'				=> 'Agregar entrada temporal',
	'projects:add_hours'			=> 'Agregar horas',
	'projects:generate_invoice'		=> 'Generar factura',
	'projects:no_projects'			=> 'No hay proyectos.',
	'projects:archive_proj'			=> 'Archivar proyecto',
	'projects:unarchive_proj'		=> 'Desarchivar proyecto',
	'projects:archive'				=> 'Ver archivo',
	'projects:active'				=> 'Proyectos activos',
	'projects:archived'				=> 'Proyectos archivados',
	'projects:noarchivedprojecttitle'		=> 'No hay proyectos archivados.',
	'projects:noarchivedprojecttext'		=> 'Puede archivar un proyecto desde la página del proyecto',
	'projects:allarchivedtitle'		=>	'Todos los proyectos archivados',
	'projects:templatize'			=>	'Guardar como plantilla',
	'projects:milestone_identifier' => "[Hito: :1]",
	/** End Projects **/


	/** Milestones **/
	'milestones:add'				=> 'Agregar Hito',
	'milestones:edit'				=> 'Editar Hito',
	'milestones:delete'				=> 'Borrar Hito',
	'milestones:milestone'			=> 'Hito',
	'milestones:target_date'		=> 'Fecha estimada',
	'milestones:assigned_user'		=> 'Usuario asignado',
	'milestones:select_default'		=> '-- No hay hitos --',
	'milestones:no_milestone'		=> 'Tareas sin hito',
	'milestones:add_success'		=> 'Hito ":1" agregado exitosamente!',
	'milestones:edit_success'		=> 'Hito ":1" editado exitosamente!',
	'milestones:add_failed'			=> 'Hito ":1" no pudo ser editado.',
	'milestones:edit_failed'		=> 'Hito ":1" no pudo ser agregado.',
	'milestones:are_you_sure_delete'		=> '¿Seguro que quieres borrar este hito?',
	'milestones:delete_success'		=> 'Hito ":1" eliminado exitosamente!',
	'milestones:does_not_exist'		=> 'Este hito no existe.',
	'milestones:target_date'		=>  'Fecha Estimada',
	'milestones:select_assignee_default'	=> 'Sin asignado',
	/** End Milestones **/

	/** Proposals **/
	'proposal:outline'  =>  'Bosquejo de propuesta',


	/** End Proposals **/

	/** Reminders **/

	'reminders:reminders'	=>	'Recordatorios',
	'reminders:send'		=>	'Enviar Recordatorios',
	'reminders:success'		=>	'Estos recordatorios han sido enviados!!',
	'reminders:remind'		=>  'Recordar',
	'reminders:message'		=>	'Mensaje',
	'reminders:due'			=>	'Días',
	'reminders:details'		=>	'Detalles',
	'reminders:log'			=>	'Registro',

	/** End Reminders **/


	/** Email Templates **/
	'emailtemplates:email_templates'	=>  'Plantillas de mail',
	'emailtemplates:create_template'	=>	'Crear plantilla',
	'emailtemplates:add'				=>	'Crear nueva plantilla de mail',
	'emailtemplates:edit'				=>	'Editar plantilla de mail',
	'emailtemplates:manage'				=>	'Gestionar plantillas',
	'emailtemplates:name'				=>	'Nombre del Email',
	'emailtemplates:subject'			=>	'Asunto del correo',
	'emailtemplates:days'				=>	'Rango de días',
	'emailtemplates:type'				=>	'Tipo de plantilla',
	'emailtemplates:success'			=>	'Plantilla de correo electrónico creada con éxito',
	'emailtemplates:edited'				=>	'Plantilla de correo electrónico editada con éxito',
	'emailtemplates:does_not_exist'		=>	'Plantilla de email no existe',
	'emailtemplates:deleted'			=>	'Plantilla de correo electrónico eliminada correctamente',
	'emailtemplates:delete_title'		=>	'Eliminar plantilla de correo electrónico',
	'emailtemplates:delete_message'		=>	'¿Seguro que deseas eliminar esta plantilla de correo electrónico?',


	/** End Email Templates **/

	/** Reports **/
	'reports:perclient'		=> 'por cliente',
	'reports:datefrom'		=> 'Desde',
	'reports:allclients'	=> 'Todos los clientes',
	'reports:dateto'		=> 'Para',
	'reports:byclient'		=> 'Cliente',

	'reports:view'			=> 'Ver reporte',
	'reports:show_all'		=> 'Mostrar reportes',

	'reports:paid_and_unpaid' => "Pagados y sin pagar",
	'reports:paid_vs_unpaid_over_time' => "Pagado vs. Sin pagar en el tiempo",
	'reports:per_client' => 'por cliente',
	'reports:total_with_tax' => "Total (con impuesto)",
	'reports:total_without_tax' => "Total (sin impuesto)",
	'reports:total_collected' => 'Total Recolectado',
	'reports:fees_paid' => 'Honorarios pagados',
	'reports:total_amount' => 'Monto total',
	'reports:paid_amount' => "Monto pagado",
	'reports:unpaid_amount' => "Monto sin pagar",
	'reports:client_name' => "Nombre del cliente",

	'reports:nodata'		=> 'Sin :1.',
	/** End Reports **/

	/** Currencies **/
	'currencies:default'	=> '[Default] :1',
	'currencies:cad'		=> 'Dolar canadiense',
	'currencies:eur'		=> 'Euro',
	'currencies:usd'		=> 'U.S. Dollar',
	'currencies:gbp'		=> 'Libra esterlina',
	'currencies:hkd'		=> 'Dolar de Hong Kong',
	'currencies:php'		=> 'Peso Philippine',
	'currencies:zar'		=> 'Rand de Sud Africa',
	/** End Currencies **/

	/** Proposals **/
	'proposals:duplicated'				=> 'Duplicated proposal #:1. The new proposal\'s number is #:2.',
	'proposals:usesectiontemplate'		=> 'Use this Section Template',
	'proposals:showcontents'			=> 'Show Contents',
	'proposals:hidecontents'			=> 'Hide Contents',
	'proposals:deletepremadesection'	=> 'Delete Section Template',
	'proposals:nopremadesections'		=> 'You have no saved section templates.',
	'proposals:newproposal'				=> 'New Proposal',
	'proposals:number'					=> 'Proposal #',
	'proposals:all'						=> 'All Proposals',
	'proposals:noproposaltitle'			=> "There are no proposals!",
	'proposals:noproposalbody'			=> "You should create a proposal now. Definitely.",
	'proposals:client_viewed'		=>	':1 viewed <a href=":2">proposal #:3</a> on :4',
	'proposals:client_accepted'		=>	':1 accepted <a href=":2">proposal #:3</a> on :4',
	'proposals:client_rejected'		=>	':1 rejected <a href=":2">proposal #:3</a> on :4',
	'proposals:rejected'				=> 'Rejected on :1',
	'proposals:accepted'				=> 'Accepted on :1',
	'proposals:lastviewed'				=> 'Last viewed by the client on :1, at :2.',
	'proposals:neverviewed'				=> 'not viewed by the client.',
	'proposals:noanswer'				=> 'No answer',
	'proposals:createproposal'			=> 'Create Proposal',
	'proposals:editproposal'			=> 'Edit Proposal',
	'proposals:createdsuccessfully'		=> 'Proposal created!',
	'proposals:sections'				=> 'Sections',
	'proposals:section'					=> 'Section',
	'proposals:createsection'			=> 'Add New Section',
	'proposals:createpage'				=> 'Add Page',
	'proposals:emptysection'			=> '(no title)',
	'proposals:emptycontents'			=> '(no contents)',
	'proposals:emptysubtitle'			=> '(no subtitle)',
	'proposals:for'						=> 'Proposal for:',
	'proposals:pagexofcount'			=> 'Page :1 of :2',
	'proposals:saving'					=> 'Saving...',
	'proposals:save'					=> 'Save Proposal',
	'proposals:savepremade'				=> 'Save as Section Template',
	'proposals:addestimate'				=> 'Add Estimate',
	'proposals:saved'					=> 'Saved!',
	'proposals:createandedit'			=> 'Next: Edit proposal contents',
	'proposals:delete_message'			=> 'Are you sure you want to delete this proposal?',
	'proposals:createpremadesection'	=> 'Add from Section Template',
	'proposals:selected_attachments'	=> 'Select Estimate',
	'proposals:attach_selected_estimate'		=> 'Attach Selected Estimate',
	'proposals:proposal'				=> 'Proposal',
	'proposals:status'					=> 'Status',
	'proposals:view'					=> 'View Proposal',
	'proposals:estimate'				=> 'Estimate',
	'proposals:no_proposals'			=> 'There are no proposals.',
	'proposals:proposal_title' => 'Proposal Title',
	'proposals:kitchennotice'			=> 'Note: Proposals will appear in the :1 once the client has viewed the proposal link. This means you can edit it all you want and the client wont see it until you want them too.',
	/** End Proposals **/

	/** Tasks **/
	'tasks:task'						=> 'Tareas',
	'tasks:edit_succeeded'				=> 'Editada la tarea con éxito.',
	'tasks:hours'						=> 'Horas',
	'tasks:due_date'					=> 'Fecha de vencimiento',
	'tasks:is_completed'				=> 'Completado?',
	'tasks:timer'						=> 'Timer',
	'tasks:rate'						=> 'Tarifa',
	'tasks:default_rate'				=> 'Tarifa por defecto',
	'tasks:entries'						=> 'Entradas de tiempo',
	'tasks:view_entries'				=> 'Ver entradas',
	'tasks:edit_entry'					=> 'Editar entrada',
	'tasks:create'						=> "Agregar tarea",
	'tasks:create_sub'					=> "Agregar sub-tarea",
	'tasks:task_parent'					=> "Tarea Padre",
	'tasks:edit'						=> "Editar tarea",
	'tasks:create_succeeded'			=> "La tarea ha sido creada!",
	'tasks:no_task_title'				=> 'Hmm, no hay tareas aún...',
	'tasks:no_task' => "No hay tareas",
	'tasks:no_task_message'				=> 'Debes crear tareas!',
	'tasks:is_viewable'					=> 'Visible en el área del cliente?',
	'tasks:no_milestones'				=> 'Tareas sin hitos asociados',
	'tasks:not_related_to_a_task'		=> "-- No relacionado a una tarea --",
	'tasks:select_parent_default'		=> '-- Sin tarea padre --',
	'tasks:timers_running'				=>	'Relojes corriendo',
	'tasks:task_completed_by'			=>	':1 Completada <a href=":2">tarea :3</a> a las :4',
	'tasks:discussion'					=>	'Discución: ',
'tasks:billed_hours' => "Horas facturadas",
	'tasks:unbilled_hours' => "Horas sin facturar",


	/** Users **/
	'users:create_user'					=> 'Crear usuario',
		'users:confirm_delete_emphasised' => "No hay vuelta atrás!",

	/** Items **/
	'items:name'						=> 'Nombre del ítem',
	'items:description'					=> 'Descripción del ítem',
	'items:qty_hrs'						=> 'Cant / Hrs',
	'items:quantity'					=> 'Cantidad',
	'items:rate'						=> 'Tarifa',
	'items:tax_rate'					=> 'Impuesto',
	'items:cost'						=> 'Costo',
	'items:line_items'					=> 'Elementos de línea',
	'items:add'							=> 'Agregar Ítem',
	'items:edit'						=> 'Editar Ítem',
	'items:noitemtitle'					=>	'No tienes ítems aún!',
	'items:noitembody'					=>	'Deberías agregar ítems ahora, facilita la creación de facturas',
	'items:delete_title'				=>	'Borrar este ítem?',
	'items:delete_message'				=>	'Estás seguro que quieres borrar este ítem ":1"?',
	'items:type'						=> 'Tipo',
	'items:select_standard'				=> 'Estándar',
	'items:select_expense'				=> 'Gasto',
	'items:add_expense_to_project'		=> 'Agregar gasto',
	'items:expenses'					=> 'Gastos',
	/** END Items **/

	/** Expenses **/
	'expenses:expenses'					=>	'Gastos',
	'expenses:add'						=>	'Agregar gasto',
	'expenses:edit_expense'				=>	'Editar gasto',
	'expenses:delete'					=>	'Borrar gasto',
	'expenses:deleted'					=>	'Gasto eliminado',
	'expenses:all'						=>	'Todos los gastos',
	'expenses:amount'					=>	'Monto',
	'expenses:supplier'					=>	'Proveedor',
	'expenses:suppliers'				=>	'Proveedores',
	'expenses:category'					=>	'Categoría',
	'expenses:categories'				=>	'Categorías',
	'expenses:add_supplier'				=>	'Añadir Proveedor',
	'expenses:edit_supplier'			=>	'Editar Proveedor',
	'expenses:add_category'				=>	'Añadir categoría',
	'expenses:edit_category'			=>	'Editar categorías',
	'expenses:parent_category'			=>	'Categoría superior',
	'expenses:filter'					=>	'Filtrar gastos',
	'expenses:start_date'				=>	'Fecha de inicio',
	'expenses:end_date'					=>	'Fecha de término',


	/** END Expenses **/

	/** Transactions **/
	'transactions:paymentcancelled'				=> 'Pago cancelado',
	'transactions:extrapaymentcancelled'		=> 'El pago ha sido cancelado.',
	'transactions:paymentreceived'				=> 'Pago recibido!',
	'transactions:fee_applied'					=> 'Como :1 impone una cuota por transacción, hemos agregado un recargo de :2%.',
	'transactions:orderbeingprocessed'			=> 'Por favor espere, su pedido se está procesando y usted será redirigido a la :1 Página.',
	'transactions:ifyouarenotredirected'		=> 'Si no se te redirige automáticamente a :1 en 5 segundos ...',
	'transactions:thankyouforyourpayment'		=> 'Gracias por su pago. Recibirás un recibo por correo electrónico en breve.',
	'transactions:ifyouhavefilesyouwillgetanemail'		=> 'Si tiene archivos en espera, recibirás un correo electrónico con un enlace para descargar en breve.',
	'transactions:ifyoudonotreceiveemail'		=> 'Si no recibes un correo electrónico dentro de una hora por favor póngase en contacto con :1',
	/** End Transactions **/

	/** Timesheets **/
	'timesheet:taskname'			=> 'Nombre de la tarea',
	'timesheet:starttime'			=> 'Hora de inicio',
	'timesheet:endtime'				=> 'Hora de término',
	'timesheet:timeframe'			=> 'Período de tiempo',
	'timesheet:duration'			=> 'Duración',
	'timesheet:date'				=> 'Fecha',
	'timesheet:forproject'			=> 'Horas para el proyecto ":1"',
	'timesheet:timesheet'			=> 'Horas',
	'timesheet:for'					=> 'Horas para:',
	'timesheet:totalbillable'		=> 'Total de horas facturables',
	'timesheet:view_pdf'			=> 'Ver horas',
	'timesheet:user'			    => 'Usuario',
	'timesheet:entries'			    => 'Entradas',
		'timesheet:no_entries'                  => "No hay entradas de tiempo.",
	/** End Timesheets **/


	/** Support Tickets **/

	'tickets:all_tickets'			=>	'Tickets de soporte',
		'tickets:support_tickets' => "Tickets de soporte",
	'tickets:pending'				=>	'Pendientes',
	'tickets:open'					=>	'Abiertos',
	'tickets:resolved'				=>	'Resueltos',
	'tickets:closed'				=>	'Cerrados',
	'tickets:respond'				=>	'Responder ticket',
	'tickets:ticket_options'		=>	'Opciones de ticket',
	'tickets:attachment'			=>	'Adjuntos',
	'tickets:updated_status'		=>	'El estado del ticket :1 ha sido actualizado a :2',
		'tickets:add_a_new_ticket' => "Agregar nuevo ticket",
		'tickets:create_a_new_ticket' => 'Crear nuevo ticket',
		'tickets:add_ticket' => 'Agregar ticket',
		'tickets:assign_to_user' => 'Asignar a usuario',
		'tickets:select_client' => 'Seleccionar cliente',
		'tickets:ticket_subject' => 'Asunto del ticket',
		'tickets:ticket_message' => 'Mensaje del ticket',
		'tickets:ticket_priority' => 'Prioridad del ticket',
		'tickets:ticket_status' => 'Estado del ticket',
		'tickets:no_priority' => '-- Sin prioridad --',
		'tickets:no_status' => '-- Sin estado --',
		'tickets:no_posts' => "Sin mensaje.",

	/** End Support Tickets **/

	/** Frontend **/
	'frontend:hithere'						=> 'Hola!',
	'frontend:followthemaillinkdude'		=> 'Para ver tu factura debes hacer click en el enlace completo enviado en el correo electrónico. Por ejemplo, :1.',
	'frontend:contactadminforassistance'	=> 'Por favor haz eso o contacta a :1 al :2 para ayuda',
	/** End Frontend **/

	/** Settings **/

	'settings:task_statuses'						=> "Estados de tareas",
	'settings:ticket_statuses'						=> "Estados de tickets",
	'settings:ticket_priorities'					=> "Prioridades de tickets",
	'settings:background_color'						=> "Color de fondo",
	'settings:text_color'							=> "Color de texto",
	'settings:text_shadow'							=> "Sombra de texto",
	'settings:box_shadow'							=> "Sombra de caja",
	'settings:default_rate'							=> "Valor por defecto",
	'settings:allowed_extensions'					=> 'Extensiones de subida permitidas',
	'settings:comma_separated'						=> 'separadas por comas',
	'settings:pdf_page_size'						=> 'Tamaño de página PDF',
	'settings:default_invoice_notes'				=> 'Default Invoice Notes',
	'settings:default_invoice_title'				=> 'Default Invoice Title',
	'settings:default_invoice_due_date'				=> 'Default Invoice Due Date',
	'settings:autosave_proposals'					=> 'Autosave Proposals',
	'settings:default_invoice_due_date_explain'		=> 'days after invoice is created. If you don\'t want a default date, leave this empty.',
	'settings:testemailsettings'					=> 'Test Email Settings',
	'settings:kitchen_route'						=> 'Client Access Link Prefix',
	'settings:kitchen_route_explain'				=> "(Preview: :1)",
	'settings:include_remittance_slip'				=> 'Remittance Slips',
	'settings:include_remittance_slip_explain'		=> "If checked, invoice PDFs will include a remittance slip.",
	'settings:items_per_page'						=> 'Items Per Page',
	'settings:items_per_page_explain'				=> 'Number of items (invoices/estimates/proposals/projects/tasks) to show per page.',
	'settings:send_x_days_before'					=> 'Default "send days before"',
	'settings:send_x_days_before_explain'			=> "Default number of days before a recurring invoice is due to send it to a client.",
	'settings:file_to_import'						=> 'File To Import',
	'settings:file_should_be_csv'					=> 'Pancake will automatically process your file and import everything in it. If Pancake is unable to process your file, it will let you know, and it will give you the option to send us some information to help us make Pancake work with your file.',
	'settings:importnow'							=> 'Import now!',
	'settings:whatimporting'						=> 'What are you importing?',
	'settings:whatexporting'						=> 'What are you exporting?',
	'settings:nouploadedimportfile'					=> 'You did not upload a file to import.',
	'settings:import'								=> 'Import',
	'settings:importedclients'						=> 'Imported :1 clients successfully.',
	'settings:importedprojects'                                         => "Imported :1 projects successfully.",
	'settings:importedusers'                                            => "Imported :1 users successfully.",
	'settings:importedinvoices'						=> 'Imported :1 invoices successfully.',
	'settings:importedtasks'						=> 'Imported :1 tasks successfully.',
	'settings:importedestimates' => 'Imported :1 estimates successfully.',
	'settings:importedtime_entries'					=> 'Imported :1 time entries successfully.',
	'settings:xwereduplicates'						=> ':1 were duplicates, and were ignored.',
	'settings:import_desc'							=> 'Import data into Pancake.',
	'settings:export'								=> 'Export',
	'settings:exportnow'							=> 'Export now!',
	'settings:importexport'							=> 'Import / Export',
	'settings:removelogo'							=> 'Remove Logo',
	'settings:wrong_license_key'					=> 'The license key you have entered is not valid.',
	'settings:noopenssl'							=> 'Your PHP server does not have OpenSSL configured, which means you can\'t use Gmail or Google Apps for sending email. Please contact your host and let them know you need OpenSSL.',
	'settings:logoremoved'							=> 'Logo removed successfully!',
	'settings:save'									=> 'Save Settings',
	'settings:logodimensions'						=> 'The logo can be uploaded in any size, and will be resized automatically.',
	'settings:logoformatsallowed'					=> 'BMP, PNG, JPG (JPEG) and GIF are allowed.',
	'settings:ftp_user'								=> 'FTP User',
	'settings:ftp_pass'								=> 'FTP Password',
	'settings:ftp_path'								=> 'FTP Path',
	'settings:ftp_port'								=> 'FTP Port',
	'settings:ftp_pasv'								=> 'Passive Mode?',
	'settings:nophpupdates'							=> "Because of the way your server is configured, you need to enter your FTP details so that Pancake can update itself. These details are used internally by Pancake and are never transmitted to anyone.",
	'settings:ftp_host'								=> 'FTP Host',
	'settings:uptodate'								=> 'Pancake is up to date (:1)',
	'settings:newversionavailable'					=> 'There is a new version of Pancake available (:1)!',
	'settings:updatenow'							=> 'Update now!',
	'settings:checkforupdates' => "Check for updates",
	'settings:youneedtoconfigurefirst'				=> 'Your Pancake is not yet configured to update itself. Please enter your FTP details below, then press "Save Settings".<br /> Pancake will then let you update.',
	'settings:general'								=> 'General',
	'settings:emails'						=> 'Emails',
	'settings:taxes'								=> 'Taxes',
	'settings:currencies'							=> 'Currencies',
	'settings:branding'								=> 'Branding',
	'settings:payment_methods'						=> 'Payments',
	'settings:feeds'								=> 'Feeds',
	'settings:api_keys'								=> 'API Keys',

	'settings:time_entry_times' => "Time Entry Times",
	"settings:include_dates_and_times_in_line_items" => 'Include dates and times in "Time Entry" line item descriptions.',
	"settings:when_generating_invoice" => "When generating invoices, use a line item per",
	"settings:use_utf8_font" => "Use UTF-8 font in PDFs",
	"settings:use_utf8_font_explanation" => "Use this if characters are broken in your PDFs.",
	"settings:pdf_attachments" => "PDF Attachments",
	"settings:pdf_attachments_explanation" => "If checked, Pancake will attach the corresponding PDF to invoice, estimate or proposal emails.",
	"" => "",
	"" => "",
	"" => "",
	"" => "",
	"" => "",



	'settings:site_name'			=> 'Nombre del sitio',
	'settings:language'				=> 'Lenguaje',
	'settings:timezone'				=> 'Huso horario',
	'settings:notify_email'			=> 'mail de notificaci´øn',
	'settings:currency'				=> 'Moneda',
	'settings:theme'				=> 'Tema de front',
	'settings:admin_theme'			=> 'Tema de admin',
	'settings:admin_name'			=> 'Nombre de admin',
	'settings:date_format'			=> 'Formato de fecha',
	'settings:time_format' => "Formato de hora",
	'settings:task_time_interval'	=> 'Redondeo de entrada temporal (Dejar en blanco para no redondear)',
	'settings:task_time_interval_description' => '(ej 0:30 o 0,5 - todas las entradas de tiempo se redondean a la más cercana doce y media cuando se factura por ellos en una factura.)',
	'settings:mailing_address'		=> 'Dirección de correos',

	'settings:default_subject'			=> 'Asunto predeterminado',
	'settings:default_contents'			=> 'Mensaje del asunto',
	'settings:new_estimate'				=> 'Nueva estimación',
	'settings:new_invoice'				=> 'Nueva factura',
	'settings:new_proposal'				=> 'Nuevo presupuesto',
	'settings:paid_notification'		=> 'Notificación de pago',
	'settings:payment_receipt'			=> 'Recibo de pago',
	'settings:new_ticket'				=> 'Nuevo ticket',
	'settings:ticket_invoice'			=> "Nuevo ticket de factura",
	'settings:ticket_updated'			=> 'Ticket actualizado',
	'settings:ticket_status_updated'	=> 'Estado del ticket actualizado',

	'settings:logo'					=> 'Tu logo',
	'settings:frontend_css'			=> 'CSS personalizado para Frontend',
	'settings:backend_css'			=> 'CSS personalizado para Backend ',

	'settings:rss_password'			=> 'Password del RSS',
	'settings:default_feeds'		=> 'Default Feeds',
	'settings:cron_job_feed'		=> 'Cron Job',
	'settings:feed_generator'		=> 'Feed Generator',
	'settings:your_link'			=> 'Your Link',
	'settings:bcc'					=> 'BCC',
	'settings:automaticallybccclientemail'		=> 'Automatically send a copy of all client emails to the notify email (defined above)',
	'settings:api_note'				=> 'Name / Note',
	'settings:api_key'				=> 'Key',

	'settings:tax_name'				=> 'Tax Name',
	'settings:tax_value'			=> 'Value',
	'settings:tax_reg'				=> 'Registration / Code',
	'settings:add_tax'				=> 'Add Another Tax',

	'settings:currency_name'		=> 'Currency Name',
	'settings:currency_code'		=> 'Currency Code',
	'settings:exchange_rate'		=> 'Exchange Rate',
	'settings:add_currency'			=> 'Add Another Currency',
	/** End Settings **/

	'update:ifyourenotsurecontactus'		=> "If you're not sure what to do, please <a href='http://pancakeapp.com/forums/newtopic/2/'>start a new tech support topic in the forums</a>.",
	'update:youmodified'					=> 'You modified',
	'update:youdeleted'						=> 'You deleted',
	'update:loadingpleasewait'				=> 'Loading, please wait...',
	'update:errordownloading'				=> 'An update to Pancake is available, but Pancake is having problems downloading it.',
	'update:herearestepstofix'				=> 'Here are a few steps you can try to fix it:',
	'update:makesureuploadsiswritable'		=> 'Make sure that your uploads folder is writable (CHMOD 0777).',
	'update:deletepancakesystemupdate'		=> 'Delete the pancake-update-system folder (inside the uploads folder), and all its contents.',
	'update:loadpancakeagain'				=> "Load Pancake again. If the error persists, change the owner of the Pancake folder (chown) so it matches the web server's user. If you can't do that, or don't know how to, please send an email to support@pancakeapp.com, and we'll help you.",
	'update:whatschanged'					=> "What's new in :1",
	'update:ftp_conn'						=> 'Pancake could not connect to the FTP host.',
	'update:ftp_login'						=> 'Pancake could not login via FTP (wrong FTP username/password?).',
	'update:ftp_chdir'						=> 'Pancake could not set the FTP path (path probably does not exist).',
	'update:ftp_no_uploads'					=> 'Pancake could not obtain permission to upload files via FTP.',
	'update:ftp_indexwrong'					=> 'The FTP Path you entered is incorrect. It should be the path to Pancake\'s directory.',
	'update:ftp_indexnotfound'				=> 'The FTP Path you entered is incorrect. It should be the path to Pancake\'s directory.',
	'update:update_conflict'				=> 'You modified some files since the last update. In order to safeguard your customizations, here is a list of files that you have modified, that conflict with the latest upgrade.',
	'update:update_no_perms'				=> 'Pancake does not have enough permissions to update itself, nor does it have access to an FTP account from which it can update itself. Update cannot continue.',
	'update:review_files'					=> 'Please review these files and make backups of them before proceeding. When the upgrade is finished, you will have to re-integrate your modifications back into them. Please do not just replace the updated files with your outdated modified copies, as that may break Pancake.',
	'update:internetissues'					=> "Pancake is unable to connect to the Internet.",
	'update:pancakeneedsinternet'			=> 'For Pancake to function correctly, your server must allow it to fetch some information from the Internet (port 80).',
	'update:maybefirewall'					=> "It appears that your server is blocking Pancake from accessing the Internet. This could be a firewall issue in your server. Please contact your host for help. Ask them to allow PHP to access :1.",
	'update:nointernetaccess'				=> 'No Internet Access',
	'update:pancakeupdated'					=> 'Pancake was upgraded from :1 to :2',
	/** Action Logger  **/

	/** End Action Logger **/

	/** Partial Payments **/
	'partial:partialpayments'			=> 'Plan de pagos',
	'partial:totalamounttobepaid'		=> "Total a ser pagado por el cliente",
	'partial:amountlefttobeadded'		=> "Monto faltante a ser agregado al plan",
	'partial:amounttoobig'				=> "Monto que debe ser removido del plan",
	'partial:noamountneeded'			=> "EL plan de pagos está completo.",
	'partial:amount'        			=> 'Monto',
	'partial:add_payment'				=> 'Agregar pago',
	'partial:dueon'         			=> 'Vence el',
	'partial:addanother'     			=> 'Agregar otro pago',
	'partial:disabledforrecurring'		=> 'Facturación recurrente está limitada a un solo pago',
	'partial:paymentdetails'			=> 'Detalles de pago',
	'partial:wrongtotal'				=> 'La suma de todas las partes de su plan de pago no coincide con la cantidad total de la factura.',
	'partial:problemsaving'				=> 'Se produjo un problema al guardar el plan de pago. Por favor, inténtalo de nuevo.',
	'partial:wrongtotalbutsaved'		=> 'La suma de todas las partes del plan de pago no coincide con la cantidad total que se facturó. <br /> Se guardaron los cambios en la factura, pero que debe arreglar el plan de pago',
	'partial:problemsavingbutsaved'		=> 'Se produjo un problema al guardar el plan de pago. Por favor, inténtelo de nuevo. <br /> Se guardaron los cambios en la factura, pero no en el plan de pago.',
	'partial:savepaymentdetails'		=> 'Guardar los datos de pago',
	'partial:partpaidthanks'			=> "Esta pate de la factura ha sido pagada, gracias.",
	'partial:proceedtopayment'			=> 'Proceder al pago',
	'partial:topaynowgoto'				=> 'Para pagar ahora, dirigirse a :1',
	'partial:pay_part_x_now' => "Pagar parte #:1 de la factura ahora",
	'partial:dueondate'					=> 'vence el :1',
	'partial:paymentmethod'				=> 'Método de pago',
	'partial:paymentdate'				=> 'Fecha de pago',
	'partial:paymentstatus'				=> 'Estado de pago',
	'partial:transactionid'				=> 'ID de transacción',
	'partial:markaspaid'				=> 'Marcar como pagado',
	'partial:transactionfee'			=> 'Fee de transacción',
	/** End Partial Payments **/

	/** Payment Gateways **/
	'paypal:clickhere'					=> 'Click para proceder',
	'authorize:transaction_key'			=> 'Llave de transacción',
	'paypal:email'   					=> 'Email de PayPal',
	'paypal:fee'    					=> 'Fee (%) de Paypal',
	'paypalpro:paypalpro'				=> 'PayPal Payments Pro (BETA)',
	'paypalpro:viacreditcard'			=> 'Pagar con tarjeta de crédito',
	'cash:cash'							=> 'Dinero',
	'check:check'						=> 'Cheque',
	'moneyorder:moneyorder'				=> 'Orden de pago',
	'creditcard:creditcard'				=> 'Tarjeta de crédito',
	'banktransfer:banktransfer'			=> 'Transferencia bancaria',
	'gateways:errorupdating'			=> 'Hubo un error al actualizar la configuración del método de pago. Por favor, póngase en contacto con soporte.',
	'gateways:paymentmethods'			=> 'Metodos de pago',
	'gateways:selectpaymentmethod'		=> 'Seleccionr método de pago',
	'gateways:nogatewayused'			=> 'Ningún método utilizado: la parte no ha sido pagada',
	'gateways:completed'				=> 'Completado',
	'gateways:refunded'					=> 'Reintegrado',
	'gateways:unpaid'					=> 'Sin pagar',
	'gateways:paymentrejected'			=> 'Pago :1 rechazado',
	'gateways:rejectedemail'			=> 'Pancake fue notificado sobre el pago :1 del cliente (:2), pero fue  rechazado por :1.',
	'gateways:pending'					=> 'Pendiente',
	'gateways:returntowebsite'			=> 'Retornar a :1',
	'gateways:cc_type'					=> 'Tipo de tarjeta de crédito',
	'gateways:cc_number'				=> 'Número de la tarjeta de crédito',
	'gateways:cc_exp'					=> 'Fecha de vencimiento',
	'gateways:cc_cardholder'			=> 'Nombre en la tarjeta',
	'gateways:cc_code'					=> 'Código de seguridad',
	'gateways:payment_details'			=> 'Detalles de pago',
	'gateways:api_signature'			=> 'Firma de API',
	'gateways:api_password'				=> 'Password de API ',
	'gateways:api_username'				=> 'Usuario de API',
	/** End Payment Gateways **/

	/** Kitchen Area **/
	'kitchen:edit_comment'				=> 'Edit Comment',
	'kitchen:add_a_comment' => "Add a comment",
	'kitchen:kitchen_name' 				=>  'Client Access Area',
	'kitchen:pleaselogin' 				=>  'Please enter your Pass Phrase to access your account',
	'kitchen:nocomments'    			=>  'There are no comments yet.',
	'kitchen:comment'   				=>  'Comment',
	'kitchen:comments'  				=>  'Comments',
	'kitchen:comments_x'                            => 'Comments (:1)',
	'kitchen:file'  					=>  'File',
	'kitchen:submitcomment'				=>  'Add comment',
	'kitchen:attachment'    			=>  'Attachment',
	'kitchen:saidon'    				=>  'said on :1, at :2',
	'kitchen:subjectinvoice'			=> 'New comment for Invoice #',
	'kitchen:subjectestimate'			=> 'New comment for Estimate #',
	'kitchen:subjectproject'			=> 'New comment for Project:',
	'kitchen:subjecttask'				=> 'New comment for Task:',
	'kitchen:subjectproposal'			=> 'New comment for Proposal:',
	'kitchen:backtodashboard'   		=>  'Back to Dashboard',
	'kitchen:client_welcome'    		=>  'Client access area for:',
	'kitchen:urltosend'					=>  'Client access url',
	'kitchen:nopassphrase'  			=>  'Currently the client "Passphrase" is not set, this means that just accessing that url is all that is needed to view the client area. If you\'d like to secure it using a simple passphrase please edit this client and set one.',
	'kitchen:passphraseset'				=>  'This client has a Passphrase set up',
	'kitchen:passphrase'    			=>  'Passphrase',
	'kitchen:description'   			=>  'This is the url to send to your client to allow them to access the client access area where they can view items, such as projects and invoices, that you have made viewable.',
	'kitchen:people_in_discussion'		=>  'People chatting',

	'kitchen:latest_invoice' => 'Latest Invoice',
	'kitchen:unpaid_balance' => 'Unpaid Balance: :1',
	'kitchen:total_paid_to_date' => 'Total Paid To Date: :1',

	/** END Kitchen Area **/

	'store:store' => 'Store',
	'store:buy' => "Buy ($:1)",
	'store:update' => "Update",
	'store:install' => "Install",
	'store:settings' => "Settings",
	'store:already_bought' => "You've already purchased this item!",
	'store:installed_successfully' => "You've installed the :1 :2 successfully.",
	'store:plugin' => "Plugin",
	'store:payment_gateway' => "Payment Gateway",
	'store:frontend_theme' => "Frontend Theme",
	'store:backend_theme' => "Backend Theme",
	'store:unknown' => "Unknown",
	'store:updatestoreitems' => "Update store items",
	'store:download_free' => "Download (FREE)",
	'store:error1000' => "Your authorization token is no longer valid. You will have to enter your payment details in pancakeapp.com once more.",
	'store:error1001' => "You have already purchased this store item!",
	'store:error1002' => "A problem occurred while trying to charge your credit card. Try again later.",
	'store:error1003' => "You have made an invalid request.",

	'email_templates:new_invoice' => 'Nueva factura',
	'email_templates:new_estimate' => 'Nuevo presupuesto',
	'email_templates:new_proposal' => 'Nueva propuesta',
	'email_templates:invoice_payment_notification_for_admin' => 'Notificación de pago (enviado al admin)',
	'email_templates:invoice_payment_notification_for_client' => 'Notificación de recibo de pago (enviada al cliente)',
	'email_templates:new_ticket' => 'Nuevo ticket',
	'email_templates:new_ticket_invoice' => 'Nueva factura de ticket',
	'email_templates:ticket_updated' => 'Notificación de actualización de Ticket',
	'email_templates:ticket_status_updated' => 'Notificación de actualización de estado de Ticket',
	'email_templates:assigned_to_task' => "Notificación de asignación de tarea",
	'email_templates:assigned_to_milestone' => "Notificación de asignación de hito",
	'email_templates:new_comment' => "Nueva notificación de comentario",

	'global:timer_app' => "Aplicación de tiempo",

	/** Dashboard **/


	/** END Dashboard **/

	# v4.0.5

	'invoices:lastreoccurrence' => 'Última reocurrencia: :1',

	# Begin v4.1.2 changes
	'invoices:converted_to_estimate' => "Factura #:1 convertida en presupuesto.",
	'global:converttoestimate' => 'Convertir a presupuesto',
	# End v4.1.2 changes

	# Begin v4.1.3 changes
	'tickets:view_archived' => "Cer tickets archivados",
	'tickets:view_unarchived' => "Ver tickets activos",
	'tickets:archiving_ticket' => "Archivando ticket",
	'tickets:unarchiving_ticket' => "Desarchivar ticket",
	"tickets:unknown_error_ticket_not_altered" => "Un error ha ocurrido. El ticket no ha sido alterado.",
	# End v4.1.3 changes

	# Begin v4.1.4 changes
	"tasks:starting_timer" => "Starting timer",
	"tasks:stopping_timer" => "Stopping timer",
	"global:all_comments" => "All Comments",
	"dashboard:view_all_comments" => "View All Comments",
	"dashboard:latest_comments" => "Latest Comments",
	"dashboard:written_by" => "Written by :1 on :2",
	"dashboard:client_activity" => "Client Activity",
	"dashboard:view_all_client_activity" => "View All Client Activity",
	"dashboard:team_activity" => "Team Activity",
	"dashboard:view_all_team_activity" => "View All Team Activity",
	"dashboard:my_tasks" => "My Tasks",
	"dashboard:view_all_my_tasks" => "View All My Tasks",
	"dashboard:what_the_team_is_working_on" => "What the team is working on.",
	# End v4.1.4 changes

	# Begin v4.1.6 changes
	"global:save_milestone" => "Guardar hito",
	"global:save_task" => "Guardar tarea",
	"global:private_comment" => "Este comentario es privado, tu cliente no lo puede ver.",
	"global:clients_cant_see_private" => "Los clientes no pueden ver comentarios privados.",
	"global:is_private" => "Privado?",
	# End v4.1.6 changes

	# Begin v4.1.7 changes
	"tickets:disable_client" => "-- Deshabilitar tickets de soporte --",
	# End v4.1.7 changes

	# Begin v4.1.8 changes
	"global:css" => "Custom CSS",
	"global:js" => "Custom JavaScript",
	"global:js_explanation" => "You can use jQuery at will. Your code will be added just before &lt;/body&gt;.",
	"settings:frontend_js" => "Frontend Custom JavaScript",
	"settings:backend_js" => "Backend Custom JavaScript",
	# End v4.1.8 changes

	# Begin v4.1.9 changes
	"proposals:estimate_number_and_amount" => "Presupuesto #:1 (:2)",
	# End v4.1.9 changes

	# Begin v4.1.10 changes
	"clients:delete" => "Borrar cliente",
	# End v4.1.10 changes

	# Begin v4.1.11 changes
	"global:nolongerexists" => "[YA NO EXISTE]",
	"global:billed_amount" => "Monto facturado",
	"global:unbilled_amount" => "Monto sin facturar",
	"global:is_billed" => "Facturado?",
	# End v4.1.11 changes

	# Begin v4.1.14 changes
	"settings:year_start" => "Comienzo del año fiscal",
	"dashboard:since_explanation" => "Desde el :1",
	# End v4.1.14 changes

	# Begin v4.1.15 changes
	"export:invoices_csv" => "Facturas (CSV)",
	# End v4.1.15 changes

	# Begin v4.1.17 changes
	"projects:createdtemplate" => "Plantilla de proyecto creado. Ahora puedes crear proyectos basados en esta plantilla.",
	"projects:delete_template" => "Borrar plantilla",
	"projects:deleted_template" => "Éxito! Plantilla eliminada.",
	# End v4.1.17 changes

	# Begin v4.1.19 changes
	"export:expenses_csv" => "Gastos (CSV)",
	"export:clients_csv" => "Clientes (CSV)",
	"projects:expense_date" => "Fecha de gastos",
	# End v4.1.19 changes

	# Begin v4.1.20 changes
	"clients:can_create_support_tickets" => "Permitir al cliente para crear tickets de soporte?",
	"tickets:submit_new" => "Enviar ticket",
	"global:cancel" => "Cancelar",
	"global:timers" => "Timers",
	"global:more" => "Más",
	# End v4.1.20 changes

	# Begin v4.1.23 changes
	"global:search" => "Search",
	"authorize:api_login_id" => "API Login ID",
	"authorize:api_login_id_description" => "You can find this in Authorize.net, under Account > API Login ID and Transaction Key.",
	"authorize:md5_hash" => "MD5-Hash",
	"authorize:md5_hash_description" => "By default, this is your API Login ID. You can change this in Authorize.net, under Account > MD5-Hash. If you see 'Hash Value Set: No', leave this empty.",
	"transactions:paymentfailed" => "Payment Failed",
	"transactions:extrapaymentfailed" => "An unknown problem occurred while trying to process your payment. Please contact :1 at :2 for assistance.",
	# End v4.1.23 changes

	# Begin v4.1.24 changes
	"projects:tracked" => "Tracked",
	"settings:accounting_type" => "Reporting Method",
	"settings:accrual" => "Show invoices based on when they were created",
	"settings:cash" => "Show invoices based on when they were paid",
	"reports:selection_explanation_accrual" => "Invoices are shown based on when they were created.",
	"reports:selection_explanation_cash" => "Paid invoices are shown based on the date of their payment.\n\nUnpaid or partially-paid invoices are shown based on when they were created.",
	"invoices:partially_paid" => "Partially",
	# End v4.1.24 changes

	# Begin v4.1.27 changes
	"global:projects_ommitted" => ":1 proyectos no mostrados",
	"global:tasks_ommitted" => ":1 tareas no mostradas",
	# End v4.1.27 changes

	# Begin v4.1.28 changes
	"login:username_email" => "Usuario / Email",
	# End v4.1.28 changes

	# Begin v4.1.31 changes
	"settings:when_new_updates_are_available" => "When new updates are available",
	"settings:dont_install_just_notify_me" => "Don't install, just notify me",
	"settings:install_automatically" => "Install automatically",
	"settings:loading_update_details" => "Loading update details... This may take a minute or two. Feel free to refresh at any time.",
	"settings:updating_please_wait" => "Updating, please wait. This page will refresh once the update has finished.",
	"settings:will_have_to_overwrite_single_file" => "Pancake will have to overwrite 1 file that you have modified manually!",
	"settings:will_have_to_overwrite_multiple_files" => "Pancake will have to overwrite :1 files that you have modified manually!",
	"settings:checking_for_updates" => "Checking for updates, please wait. This page will refresh automatically.",
	"settings:updating_please_wait" => "Updating, please wait. This page will refresh once the update has finished.",
	"settings:description" => "Save your updated settings before changing tab or leaving the page.",
	"settings:business_identities" => "Business Identities",
	"settings:business_name" => "Business Name",
	"settings:new_business" => "New Business",
	"settings:business_identity" => "Business Identity",
	"settings:business_identity_explanation" => "Your client will see the above business identity on all of their emails, PDFs and pages.",
	# End v4.1.31 changes

	# Begin v4.1.33 changes
	"settings:have_been_updated" => 'The settings have been updated.',
	"tasks:all" => "All Tasks",
	"projects:progress" => "Progress",
	"expenses:name" => "Expense Name",
	"tasks:add_hours_to" => "Add Hours To :1",
	"global:today" => "Today",
	"global:yesterday" => "Yesterday",
	"global:other" => "Other",
	"global:now" => "Now",
	"timesheet:view_for_clients" => "View timesheet (for clients)",
	"global:not_billed_yet" => "Not billed yet.",
	"tasks:total_logged_time" => "Total logged time",
	"global:biweekly" => "Biweekly",
	# End v4.1.33 changes

	# Begin v4.2 changes
	'settings:default_task_due_date' => 'Default Task Due Date',
	'settings:default_task_due_date_explain' => "days after task is created. If you don't want a default date, leave this empty.",
	# End v4.2 changes

);

/** End of file: pancake_lang.php **/
